### 1. Import numpy as np and see the version

In [3]:
import numpy as np
print(np.__version__)

1.14.0


### 2. How to create a 1D array?

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. How to create a boolean array?

In [7]:
arr = np.full((3,3), True, dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 4. How to extract items that satisfy a given condition from 1D array?

In [9]:
arr = np.arange(10)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

### 5. How to replace items that satisfy a condition with another value in numpy array?

In [10]:
arr = np.arange(10)
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 6. How to replace items that satisfy a condition without affecting the original array?

In [12]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 7. How to reshape an array?

In [13]:
np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 8. How to stack two arrays vertically?

In [17]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# Method 1:
np.concatenate([a, b], axis=0)
# Method 2:
np.vstack([a, b])
# Method 3:
np.r_[a, b]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 9. How to stack two arrays horizontally?

In [19]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# Method 1:
np.concatenate([a, b], axis=1)
# Method 2:
np.hstack([a, b])
# Method 3:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 10. How to generate custom sequences in numpy without hardcoding?

In [22]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### 11. How to get the common items between two python numpy arrays?

In [24]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

### 12. How to remove from one array those items that exist in another?

In [26]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### 13. How to get the positions where elements of two arrays match?

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

### 14. How to extract all numbers between a given range from a numpy array?

In [39]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]
# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
# Method 3:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

### 15. How to make a python function that handles scalars to work on numpy arrays?

In [41]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

### 16. How to swap two columns in a 2d numpy array?

In [44]:
arr = np.arange(9).reshape(3,3)
# arr
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### 17. How to swap two rows in a 2d numpy array?

In [45]:
arr = np.arange(9).reshape(3,3)
# arr
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### 18. How to reverse the rows of a 2D array?

In [47]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### 19. How to reverse the columns of a 2D array?

In [49]:
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### 20. How to create a 2D array containing random floats between 5 and 10?

In [53]:
arr = np.arange(9).reshape(3,3)
# Method 1:
np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
# Method 2
np.random.uniform(5,10, size=(5,3))

array([[5.42772091, 6.56067695, 8.82965408],
       [6.77708824, 5.2652927 , 5.48102228],
       [5.38512851, 6.33106329, 8.92455183],
       [6.5415415 , 7.69227424, 8.21439003],
       [5.68098736, 9.92473184, 5.29357526]])

### 21. How to print only 3 decimal places in python numpy array?

In [55]:
rand_arr = np.random.random((5,3))
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.225, 0.411, 0.769],
       [0.565, 0.493, 0.828],
       [0.572, 0.869, 0.193],
       [0.236, 0.444, 0.759]])

### 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [58]:
np.set_printoptions(suppress=True, precision=6)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

### 23. How to limit the number of items printed in output of numpy array?

In [59]:
np.set_printoptions(threshold=6)
np.arange(15)

array([ 0,  1,  2, ..., 12, 13, 14])

### 24. How to print the full numpy array without truncating

In [63]:
np.set_printoptions(threshold=np.nan)
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [65]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)